#!/bin/bash
# https://alkusin.net/crubuntung
#Modifié par Jambalak 

bypass() {
  sudo -v
  while true;
  do
    sudo -n true
    sleep 45
    kill -0 "$$" || exit
  done 2>/dev/null &
}

readonly txt1="Mise à jour..."
readonly txt2="Installation..."
readonly txt3="Configuration..."
readonly txt4="Terminé !"
readonly txt5="Appuyez sur ENTRÉE pour redémarrer."

bypass

clear
  printf "$txt1\n\n"
  sleep 3s
    sudo apt -y update
    sudo apt -y upgrade

clear
  printf "$txt2\n\n"
  sleep 3s
    echo  msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
#	sudo addgroup netdev
#    sudo usermod -a -G netdev $USER
#    sudo usermod -a -G video $USER
     sudo apt -y install adwaita-icon-theme-full audacity brightness-udev brightnessctl compton conky-all cpufrequtils cups cups-daemon dmz-cursor-theme filezilla firefox-esr fonts-croscore fonts-hack fonts-lato fonts-noto-color-emoji fonts-vollkorn galculator galternatives gdebi geoclue-2.0 gimp gimp-gmic git gsimplecal gtk-update-icon-cache gtk3-nocsd gufw gvfs hardinfo htop imagemagick inkscape kazam libgdk-pixbuf2.0-dev libglib2.0-dev libreoffice libreoffice-style-* libxml2-utils lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings lsb-release mesa-utils mesa-utils-extra mesa-vulkan-drivers mousepad neofetch nitrogen numlockx obconf menu obsession openbox optipng orage parole pavucontrol pitivi policykit-1-gnome gnome-font-viewer redshift-gtk ristretto ruby-sass scrot simple-scan software-properties-gtk 
     sudo apt -y install synaptic system-config-printer thunar thunar-archive-plugin thunar-volman thunderbird tint2 transmission-gtk tumbler tumbler-plugins-extra volumeicon-alsa wget xarchiver xbacklight xcalib xdg-user-dirs-gtk xdg-utils xdotool xfce4-appfinder xfce4-battery-plugin xfce4-clipman xfce4-notifyd xfce4-power-manager xfce4-screenshooter xfce4-settings xfce4-taskmanager xfce4-terminal xiccd xinit xorg xpdf xserver-xorg xz-utils plank geany unzip 7zip xrdp
sudo adduser xrdp ssl-cert
sudo systemctl restart xrdp
clear
  printf "$txt3\n\n"
  sleep 3s
	sudo update-alternatives --set x-session-manager /usr/bin/openbox-session
#    cd /tmp/
#    wget https://www.dropbox.com/s/gb3tm6r51sk99th/crubuntung-files.tar.xz?dl=0
#    tar Jxvf 'crubuntung-files.tar.xz'
#    chmod +x crubuntung-files/etc/skel/.bin/crubuntung-scripts/*
    #mv -f crubuntung-files/english-conkyrc crubuntung-files/etc/skel/.conkyrc
    #mv -f crubuntung-files/english-menu.xml crubuntung-files/etc/skel/.config/openbox/menu.xml
    #mv -f crubuntung-files/english-lite-menu.xml crubuntung-files/etc/skel/.config/openbox/menu.xml
    #mv -f crubuntung-files/lite-autostart crubuntung-files/etc/skel/.config/openbox/autostart
    #mv -f crubuntung-files/lite-menu.xml crubuntung-files/etc/skel/.config/openbox/menu.xml
   # \cp -r crubuntung-files/etc/skel/. ~/
   # sudo \cp -r crubuntung-files/etc/. /etc
   # sudo \cp -r crubuntung-files/usr/. /usr
   # rm -rf crubuntung-files/
   # mkdir ~/.crubuntung-backup/
   # sh ~/.bin/crubuntung-scripts/theme-crunchified.sh
    #mv crubuntung-files.tar.xz ~/.crubuntung-backup/
    #cp -r /usr/share/icons/Papirus/ /usr/share/themes/Numix/ ~/.crubuntung-backup/
clear
  printf "$txt4\n\n"
read -p "$txt5"
systemctl reboot
